[versions]
androidx-lifecycle = "2.6.0-alpha03"

compose = "1.3.0"
composeCompiler = "1.3.2"
accompanist = "0.26.5-rc"

intuit = "1.0.6"

koin = "3.2.0"
ktor = "2.1.2"

# gradlePlugin and lint need to be updated together
gradlePlugin = "7.3.1"
lintMinCompose = "30.0.0"

ktlint = "0.45.2"
kotlin = "1.7.20"
coroutines = "1.6.4"
okhttp = "3.12.13"
coil = "2.2.2"

[libraries]
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }

kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

intuit-ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "intuit" }
intuit-sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "intuit" }

io-koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
io-koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

io-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

io-ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
io-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
io-ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
io-ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
io-ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
io-ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
io-ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
