[versions]
androidx-lifecycle = "2.6.0-alpha03"

compose = "1.4.0"
composeCompiler = "1.4.0"
accompanist = "0.26.5-rc"

intuit = "1.0.6"

kmmViewmodelCore = "1.0.0-ALPHA-3"
koin = "3.2.0"
ktor = "2.1.2"

google-services = "4.3.14"

# gradlePlugin and lint need to be updated together
gradlePlugin = "7.3.1"
lintMinCompose = "30.0.0"

ktlint = "0.45.2"
kotlin = "1.8.0"
coroutines = "1.6.4"
okhttp = "3.12.13"
coil = "2.2.2"

firestore-shared = "0.2.5"
firestore-android = "24.4.5"

ksp = "1.8.0-1.0.9"
nativecoroutines = "1.0.0-ALPHA-5"
sql-delight = "1.5.5"

[libraries]
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-animation-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }

kmm-viewmodel-core = { module = "com.rickclephas.kmm:kmm-viewmodel-core", version.ref = "kmmViewmodelCore" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }

intuit-ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "intuit" }
intuit-sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "intuit" }

io-koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
io-koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

io-coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

io-ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
io-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
io-ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
io-ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
io-ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
io-ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
io-ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
io-ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

firestore-shared = { module = "co.touchlab:firestore", version.ref = "firestore-shared" }
firestore-android = { module = "com.google.firebase:firebase-firestore", version.ref = "firestore-android" }

sql-delight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sql-delight" }
sql-delight-gradle = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sql-delight" }
sql-delight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sql-delight" }
sql-delight-ios = { module = "com.squareup.sqldelight:native-driver", version.ref = "sql-delight" }

[plugins]
nativecoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "nativecoroutines" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
